"""add division and attendance permission

Revision ID: 1e4ccdeac893
Revises: 
Create Date: 2026-01-11 06:59:23.835550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4ccdeac893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('can_mark_attendance', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_user_division', 'division', ['division_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_division', type_='foreignkey')
        batch_op.drop_column('can_mark_attendance')
        batch_op.drop_column('division_id')

    op.drop_table('division')
    # ### end Alembic commands ###
