"""Add JadwalPiket, PiketAssignment, and EmailReminderLog tables

Revision ID: 258638b9f706
Revises: 75fb618c1be0
Create Date: 2026-02-05 08:19:53.683425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258638b9f706'
down_revision = '75fb618c1be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=20), nullable=False),
    sa.Column('recipients_count', sa.Integer(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_piket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', name='unique_day_of_week')
    )
    op.create_table('piket_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jadwal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jadwal_id'], ['jadwal_piket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jadwal_id', 'user_id', name='unique_jadwal_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piket_assignment')
    op.drop_table('jadwal_piket')
    op.drop_table('email_reminder_log')
    # ### end Alembic commands ###
