"""empty message

Revision ID: 74501bd91146
Revises: 1e4ccdeac893
Create Date: 2026-01-20 00:14:16.416267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74501bd91146'
down_revision = '1e4ccdeac893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notulensi',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('attendance_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'regular'"))
        batch_op.create_unique_constraint('unique_session_user', ['session_id', 'user_id'])

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('unique_division_name', ['name'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_session_pic', 'pic', ['pic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('unique_session_user', type_='unique')
        batch_op.alter_column('attendance_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'regular'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    op.drop_table('notulensi')
    # ### end Alembic commands ###
