"""Add profile picture BLOB fields

Revision ID: 75fb618c1be0
Revises: 74501bd91146
Create Date: 2026-01-25 11:10:18.837832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fb618c1be0'
down_revision = '74501bd91146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_filename')
        batch_op.drop_column('profile_picture_data')

    # ### end Alembic commands ###
