"""Auto migration from agent

Revision ID: 7d363572af7c
Revises: 258638b9f706
Create Date: 2026-02-07 19:00:42.411173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d363572af7c'
down_revision = '258638b9f706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        # Add as nullable first to allow existing rows to be backfilled
        batch_op.add_column(sa.Column('session_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    # Backfill existing rows with a sensible default ('all') then enforce NOT NULL
    op.execute("UPDATE session SET session_type = 'all' WHERE session_type IS NULL")
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('session_type', existing_type=sa.String(length=50), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('session_type')
        batch_op.drop_column('description')

    with op.batch_alter_table('pic', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
