"""Auto migration from assistant

Revision ID: 965115e48b90
Revises: 7d363572af7c
Create Date: 2026-02-07 20:21:20.134968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965115e48b90'
down_revision = '7d363572af7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_pic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pic_id'], ['pic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'pic_id', name='unique_session_pic')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('attendance_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notulensi', schema=None) as batch_op:
        batch_op.drop_constraint('notulensi_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint('session_pic_id_fkey', type_='foreignkey')
        batch_op.drop_column('pic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('session_pic_id_fkey', 'pic', ['pic_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('pic', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('notulensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notulensi_session_id_fkey', 'session', ['session_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attendance_session_id_fkey', 'session', ['session_id'], ['id'])

    op.drop_table('session_pic')
    # ### end Alembic commands ###
